"""add tabela comentarios

Revision ID: 145dbfb45a7b
Revises: 5585043692bd
Create Date: 2025-06-29 22:05:02.520204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145dbfb45a7b'
down_revision = '5585043692bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.String(length=255), nullable=False),
    sa.Column('dataHora', sa.DateTime(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('mensagem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['user.id'], name='fk_comment_user'),
    sa.ForeignKeyConstraint(['mensagem_id'], ['message.id'], name='fk_comment_message'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
