"""Add curtidas and is_deleted to Message

Revision ID: 2b37139394eb
Revises: a97a7aaa9abe
Create Date: 2025-08-13 11:06:57.963627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b37139394eb'
down_revision = 'a97a7aaa9abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curtidas', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))

    # Depois de adicionadas as colunas, se quiser, remova os defaults:
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('curtidas', server_default=None)
        batch_op.alter_column('is_deleted', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('curtidas')
    # ### end Alembic commands ###
