"""denovo

Revision ID: 6031d637cf84
Revises: bc8bbec8b801
Create Date: 2025-08-13 11:43:25.809258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6031d637cf84'
down_revision = 'bc8bbec8b801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curtidas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('curtidas')

    # ### end Alembic commands ###
