"""voltando as origens

Revision ID: bc8bbec8b801
Revises: 2b37139394eb
Create Date: 2025-08-13 11:39:41.625684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8bbec8b801'
down_revision = '2b37139394eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('curtidas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curtidas', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
